### ISSUE TITLE
[Question] There is NO  "Stop Thread" keyword.

### ISSUE THREAD

**Issue by albinsun** [robooo/robotframework-ConfluentKafkaLibrary#20]
Hi,

Thanks for the cool work of this library.
I've one question about "Start Consumer Threaded"

In https://robooo.github.io/robotframework-ConfluentKafkaLibrary/ > Example > Run Avro Consumer over HTTPS and threaded.
After "Start Consumer Threaded", there is a keyword "Stop Process" and which is not included in ConfluentKafkaLIbrary, Process and BuiltIn Library, so what library is it import from?

**Comment by robooo** [comment]
Hi @albinsun,
thank you for reaching out!
This is just a mistake in documentation due to previous implementation in threads, I will correct it in next release. For actual examples please look at [examples](https://github.com/robooo/robotframework-ConfluentKafkaLibrary/tree/master/examples) those are executed after each MR + release.
Right now the keyword is running like a daemon without any graceful stop (it's closed at the end of execution). Do you need this functionality? I think daemon will require some event notifications.

**Comment by albinsun** [comment]
Hi @robooo ,
For now, daemon notification is a nice to have but not urgent feature for me cuz I'm just start trying this project so needs some tutorial. :P
Follow your comment, those example works fine and I know how to leverage them in my robot test case. Thank you!
