### ISSUE TITLE
When Connection to Kafka is failed, the connect to kafka logs keep on coming. Can we stop/limit the retries. 

### ISSUE THREAD

**Issue by peeyushjain62-coder** [robooo/robotframework-ConfluentKafkaLibrary#31]
I am using below apis from ConfluentKafkaLibrary 1.8.2.post1

${group_id}=    Create Producer Kafka
${resp}=    list topics            group_id=${group_id}

If Kafka is not running then below error message comes:
**|FAIL|rdkafka#producer-1| [thrd:10.61.251.25:9092/bootstrap]: 10.61.251.25:9092/bootstrap: Connect to ipv4#10.61.251.25:9092 failed: Unknown error (after 2037ms in state CONNECT)**

This error message keeps on coming after every 2 seconds.

Question: Is there a way to stop/limit this message retry. How can i come out of this.

**Comment by peeyushjain62-coder** [comment]
You are right about putting some basic check and then create producer. But in my case Kafka can be present anywhere.
It can be running on RHEL Machine, SUSE Machine, kubernetes pod etc. In my code I am only taking Kafka IP and Port.

In this scenario how can i check if Kafka is running fine?
Because whenever I am using any API from ConfluentKafkaLibrary and Kafka is not running, I am getting same error as above.

**Comment by robooo** [comment]
Hard question :) it depends on situation and deployment but looking before at some logs which tell you kafka is up & running should be the best. Fastest solution is to have some minute sleep before test run, if you have docker-compose you can use something similar like this:
https://github.com/robooo/robotframework-ConfluentKafkaLibrary/blob/master/.github/workflows/main.yml#L35

so try to find which way is best for you because this is out of scope of this library, the error is just transmitted :)
